database:
  host: localhost
  port: 27017
  dbname: test-server # db name
  username: root
  password: password

serverconfig:
  port: "5050"

jwt:
  API_SECRET: yoursecretstring
  TOKEN_HOUR_LIFESPAN: 12
